name: denizen-reflect
author: meigoc
authors: ['gleb_petrovich', 'isnsest']
contributors: ['gleb_petrovich', 'isnsest']
version: ${version}
main: meigo.denizen.reflect.DenizenReflect
description: Allows Denizen scripts to directly interact with and manipulate Java objects.
website: https://github.com/meigoc/denizen-reflect
depend: [Denizen]
softdepend: [PlaceholderAPI]
api-version: '1.21'