name: denizen-reflect
author: Meigo™ Corporation
version: ${version}
main: meigo.denizen.reflect.DenizenReflect
description: Adds direct Java support to Denizen scripts.
depend: [Denizen]
softdepend: [PlaceholderAPI]
api-version: '1.21'