name: denizen-reflect
author: isnsest
version: ${version}
main: com.isnsest.denizen.reflect.DenizenReflect
description: Adds direct Java support to Denizen scripts.
depend: [Denizen]
softdepend: [PlaceholderAPI]
api-version: '1.21'