name: denizen-reflect
author: isnsest
version: 2.0
main: meigo.denizen.reflect.DenizenReflect
description: Allows Denizen scripts to directly interact with and manipulate Java objects.
depend: [Denizen]
softdepend: [PlaceholderAPI]
api-version: '1.21'